### ISSUE TITLE
Weird datetime format in SRUM database?

### ISSUE THREAD

**Issue by pbeart** [libyal/esedb-kb#2]
Sorry if this is in the wrong place but it seemed like the best way to suggest a topic for investigation, here is what I have found so far:

I've read up on ESE parsing and am writing my own parser. My biggest challenge so far has been parsing the FILETIME format, which is supposedly a number of 100s of ns since 1601/01/01.

My tests for my parsing function test with the bytes input `b'\x01\xcb\x17\x70\x1e\x9c\x88\x5a'`, which I can parse as being a time in 2010, and this all works as expected. The issue is that when I look at the timestamps in my own SRUM ESE database, I see values like `b'\xbc\xbb\xbb\xbbqe\xe5@'`, which is orders of magnitude out from being a sensible datetime, **even though Nirsoft's ESEDatabaseViewer manages to parse it as being a much more sensible time of 20/12/2019 13:18:00**.

I really don't know where to go from here, particularly since it isn't anything obvious like an endianness issue.

**Comment by joachimmetz** [comment]
What timestamp are you looking at? The format contains different types of timestamps like OLE Automation date/ See: https://github.com/libyal/esedb-kb/blob/master/documentation/System%20Resource%20Usage%20Monitor%20(SRUM).asciidoc#33-973f5d5c-1d90-4944-be8e-24b94231a174

I'm also curious why you are writing your own parser?

**Comment by joachimmetz** [comment]
No follow up original reporter, closing issue.
